server:
  port: 8080
  

logging:
  level:
    com.jatis.tripatra.demo: info

spring:
  security:
    user:
      name: demo
      password: "null"
      
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:~/demo
    username: demo
    password: password
    hikari:
      maximum-pool-size: 5
      connection-test-query: select 1
      
#service.swagger-host: 35.197.144.152/demo
